language: c
sudo: required
install:
  - ./.travis-deps.sh
  - make Q=
  - sudo make install Q=
os:
  - linux
  - osx
compiler:
  - clang
  - gcc
script:
  - cd test && ./run-tests.sh
matrix:
  include:
    - env: _="checkpatch"
      script:
        - ./.travis-checkpatch.sh
