name: Everything.

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        builder: [linux_x86-64_latest, windows_x86_latest]
        include:
          - builder: linux_x86-64_latest
            triplet: x86_64-linux-musl
            script: build-linux.sh
          - builder: windows_x86_latest
            triplet: i686-w64-mingw32
            script: build-win32.sh
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Build everything
        run: |
          cd versions
          docker run --rm -t \
            -v $PWD/../dist/${{ matrix.triplet }}:/dist \
            -v $PWD:/work \
            -v $PWD/../patches:/work/patches \
            -v $PWD/../${{ matrix.script }}:/work/${{ matrix.script }} \
            ghcr.io/zoomten/a-lot-of-rgbds-builder:${{ matrix.builder }} \
            bash ${{matrix.script}}
      - name: Upload artifact
        if: ${{ github.ref_name == 'master' }}
        uses: actions/upload-artifact@v4.3.0
        with:
          name: rgbds
          path: |
            dist/
